version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/vite-projects
    tty: true
    stdin_open: true
    command: sh -c "cd vite-project && npm run dev"
    ports:
      - "3000:3000"
